openapi: 3.0.3
info:
  title: OpenDataDiscoveryIngestion API Contract
  version: 0.0.1
  description: OpenDataDiscoveryIngestion API Contract
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /ingestion/{datasourceOddrn}/datasets:
    post:
      description: Provides list of available datasets
      operationId: postDataSetList
      tags:
        - OpenDataDiscoveryIngestion
      parameters:
        - in: path
          name: datasourceOddrn
          schema:
            type: string
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: './entities.yaml/#/components/schemas/DataSetList'
      responses:
        '200':
          description: OK
  /ingestion/{datasourceOddrn}/transformers:
    post:
      description: Provides list of available transformers
      operationId: postDataTransformerList
      tags:
        - OpenDataDiscoveryIngestion
      parameters:
        - in: path
          name: datasourceOddrn
          schema:
            type: string
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: './entities.yaml/#/components/schemas/DataTransformerList'
      responses:
        '200':
          description: OK

  /ingestion/{datasourceOddrn}/transformers/runs:
    post:
      description: Provides list of runs for all transformers
      operationId: postDataTransformerRunList
      tags:
        - OpenDataDiscoveryIngestion
      parameters:
        - in: path
          name: datasourceOddrn
          schema:
            type: string
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: './entities.yaml/#/components/schemas/DataTransformerRunList'
      responses:
        '200':
          description: OK

  /ingestion/{datasourceOddrn}/consumers:
    post:
      description: Provides list of available consumers
      operationId: postDataConsumerList
      tags:
        - OpenDataDiscoveryIngestion
      parameters:
        - in: path
          name: datasourceOddrn
          schema:
            type: string
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: './entities.yaml/#/components/schemas/DataConsumerList'
      responses:
        '200':
          description: OK
  /ingestion/{datasourceOddrn}/inputs:
    post:
      description: Provides list of available inputs
      operationId: postDataInputList
      tags:
        - OpenDataDiscoveryIngestion
      parameters:
        - in: path
          name: datasourceOddrn
          schema:
            type: string
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: './entities.yaml/#/components/schemas/DataInputList'
      responses:
        '200':
          description: OK

  /ingestion/{datasourceOddrn}/qualitytests:
    post:
      description: Provides list of available data quality tests
      operationId: postDataQualityTestList
      tags:
        - OpenDataDiscoveryIngestion
      parameters:
        - in: path
          name: datasourceOddrn
          schema:
            type: string
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: './entities.yaml/#/components/schemas/DataQualityTestList'
      responses:
        '200':
          description: OK

  /ingestion/{datasourceOddrn}/qualitytests/runs:
    post:
      description: Provides list of available data quality tests runs
      operationId: postDataQualityTestRunList
      tags:
        - OpenDataDiscoveryIngestion
      parameters:
        - in: path
          name: datasourceOddrn
          schema:
            type: string
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: './entities.yaml/#/components/schemas/DataQualityTestRunList'
      responses:
        '200':
          description: OK
